site_name: VGD Counterfactuals
theme:
  name: material
  font: 
    text: Roboto Condensed
    code: Roboto Mono
  palette:
    scheme: default
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy  # Enables copy button on code blocks
    - content.code.annotate
  highlightjs: true  # Enables syntax highlighting using highlight.js

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Get Started:
      - Core Concepts: get_started_core.md
      - Introduction by Example: get_started_example.md
  - Tutorials:
      - Using MEGAN: tutorials_megan.md